### ISSUE TITLE
using with Rserve...

### ISSUE THREAD

**Issue by darrellberry** [sgerrand/alpine-pkg-R#11]
Hi -- hoping to use this as base for a docker image which includes Rserve. At the moment, it appears than your binaries are compiled in such a way that Rserve won't work with them -- error when trying to install Rserve 1.8-5  is:

```
configure: error: R was configured without --enable-R-shlib or --enable-R-static-lib

*** Rserve requires R (shared or static) library.                       ***
*** Please install R library or compile R with either --enable-R-shlib  ***
*** or --enable-R-static-lib support                                      ***

```

Any chance of you offering a build which has those flags added, or which includes the library?

best wishes

d

**Comment by lahma** [comment]
I see that there a two branches, one for static and one for shared (static seems to have a green build). Is there any download location for these variants?

**Comment by sgerrand** [comment]
> I see that there a two branches, one for static and one for shared (static seems to have a green build). Is there any download location for these variants?

👋  @lahma: Neither of them are particularly stable at the moment. I should have time later tonight to resolve the last issues with both versions.

I'll update this issue then. 🙇

**Comment by lahma** [comment]
@sgerrand thanks for the quick reply. I just found about https://github.com/alpinelinux/aports/tree/master/community/R which seem to offer R binaries the same way via the community repos: https://pkgs.alpinelinux.org/packages?name=R and seems to have the bits that Rserve needs.

Might be beneficial to combine your forces?

**Comment by sgerrand** [comment]
@lahma: Apologies for not responding to you at the time. I'm deprecating this repository in favour of the package you referenced in the community repository and won't be making further changes to this repository or package.
